apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    TESTTTTTTTTTTTTTTTTTTTTTTTT
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: custom-ca
  namespace: openshift-config

